name: Library Compile
on: push
jobs:
  build:
    name: Test compiling 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v1.0.0
      with:
        libraries:  PciManager 
        examples-exclude: bluepill_position_control, esp32_position_control
